Update histogram.yml

diff --git a/.github/workflows/histogram.yml b/.github/workflows/histogram.yml
--- a/.github/workflows/histogram.yml
+++ b/.github/workflows/histogram.yml
@@ -20,17 +20,26 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
-          python-version: "3.10"
+          python-version: "3.x"
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install matplotlib PyGithub
+          pip install pandas matplotlib PyGithub
 
       - name: Run Histogram script
         env:
           GH_PAT: ${{ secrets.GH_PAT }}
         run: python scripts/histogram.py
+
+      - name: Check if Histogram chart is generated
+        run: |
+          if [ -f "artifacts/histogram.png" ]; then 
+            echo "✅ Histogram chart generated successfully."; 
+          else 
+            echo "❌ Histogram chart not found."; 
+            exit 1;
+          fi
 
       - name: Commit and push Histogram to artifacts/
         run: |
@@ -38,11 +47,13 @@ jobs:
           git config --global user.email 'github-actions@github.com'
 
           if [ -f artifacts/histogram.png ]; then
+            git pull origin main
             git add artifacts/histogram.png
             git commit -m "Update histogram report"
             git push origin main
           else
-            echo "Histogram not found, skipping commit."
+            echo "No histogram generated. Skipping commit."
+
 
 
 
